#!/bin/bash
rm -rf log/*
sbatch batch_fit_all_helper.sh R raw
sbatch batch_fit_all_helper.sh T raw
sbatch batch_fit_all_helper.sh V raw
sbatch batch_fit_all_helper.sh R simulated_policy_compress.filter_depth.value_path
sbatch batch_fit_all_helper.sh T simulated_policy_compress.filter_depth.value_path
sbatch batch_fit_all_helper.sh V simulated_policy_compress.filter_depth.value_path
sbatch batch_fit_all_helper.sh R simulated_policy_compress.filter_depth.value_levelmean
sbatch batch_fit_all_helper.sh T simulated_policy_compress.filter_depth.value_levelmean
sbatch batch_fit_all_helper.sh V simulated_policy_compress.filter_depth.value_levelmean
sbatch batch_fit_all_helper.sh R simulated_policy_compress.filter_depth.value_sum
sbatch batch_fit_all_helper.sh T simulated_policy_compress.filter_depth.value_sum
sbatch batch_fit_all_helper.sh V simulated_policy_compress.filter_depth.value_sum
sbatch batch_fit_all_helper.sh R simulated_policy_compress.filter_depth.value_max
sbatch batch_fit_all_helper.sh T simulated_policy_compress.filter_depth.value_max
sbatch batch_fit_all_helper.sh V simulated_policy_compress.filter_depth.value_max
